name: SonarQube Scan  # Workflow name

on:
  push:
    branches:
      - main  # Runs on pushes to the main branch
  pull_request:
    branches:
      - main  # Runs on pull requests to the main branch

jobs:
  sonar_scan:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Fetches the latest code from GitHub

      - name: Start SonarQube (Docker)
        run: |
          docker run -d --name sonarqube -p 9000:9000 sonarqube:lts
          sleep 30  # Wait for SonarQube to start

      - name: Install SonarQube Scanner
        run: |
          wget -O sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner.zip
          mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
          echo "/opt/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "http://localhost:9000"
        run: |
          sonar-scanner \
            -Dsonar.projectKey=MyProject \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN

      - name: Check SonarQube Quality Gate
        run: |
          sleep 10  # Wait for SonarQube to process the results
          STATUS=$(curl -s -u admin:admin "http://localhost:9000/api/qualitygates/project_status?projectKey=MyProject" | jq -r '.projectStatus.status')
          echo "SonarQube Quality Gate Status: $STATUS"
          if [[ "$STATUS" != "OK" ]]; then
            echo "❌ Security vulnerabilities found! Stopping pipeline."
            exit 1
          fi
